#!/usr/bin/env python3.10
from coordinates import get_gps_coordinates
from get_weather import get_weather_here

def main():
    coordinates = get_gps_coordinates()
    weather = get_weather_here()

if __name__ == '__main__':
    main()
    